### ISSUE TITLE
Spaces getting stripped out

### ISSUE THREAD

**Issue by clavinniu** [MrApplejuice/wp-autologin-links#14]
**Describe the bug**
When passing in other get variables that include properly encoded spaces are stripped out when redirected. The plugin strips out both %20 and +. 

**Please give the following details when submitting a bug**
 - Wordpress version - 5.2.4
 - Plugin version - Version 1.10.1
 - Browser - All browsers

Thanks for your time and contribution to the community.

**Comment by MrApplejuice** [comment]
Roger! Will be fixed in the next update, coming in a week!
