### ISSUE TITLE
Update to 1.10.0 Kills Site on Wordpress 5.0.3

### ISSUE THREAD

**Issue by miccks** [MrApplejuice/wp-autologin-links#7]
When the update 1.10.0 is installed the site goes down on Wordpress 5.0.3

**Comment by MrApplejuice** [comment]
Thanks for reporting! I will debug the issue now!

**Comment by MrApplejuice** [comment]
PS: Not sure why the email alert did not work, so sorry for the delay!

**Comment by MrApplejuice** [comment]
Hey there! I gave it a try and cannot reproduce the bug. Could you give me a few more details?

- Which PHP version is installed on the website you are running?
- From which plugin version did you upgrade?
- Any error logs by any chance?

**Comment by miccks** [comment]
Thanks for taking care!
- PHP Version was 5.4.45 -> I changed it to 7.2.7 and I could activate and use the plugin again with no issues!

Thank you!
