### ISSUE TITLE
Javascript not working in wp-admin/users.php

### ISSUE THREAD

**Issue by dwheelerra** [MrApplejuice/wp-autologin-links#8]
with the new update 1.10, I cannot generate new/create new/delete autologin links.
I had to move back to the previous version. 1.09

**Comment by MrApplejuice** [comment]
Hi there! Thanks for reporting! Can you give me some details? Like: Which browser you are using and which OS so that I can reproduce the bug?

**Comment by MrApplejuice** [comment]
Just asking one more time: do you have more details? Otherwise, I need to close the ticket because I do not have enough information.

**Comment by dwheelerra** [comment]
Nope, dont' have more details. Doesn't work on any theme I've tried it on. 
As soon as I do the upgrade, the admin part stops working.


Also, the pulldown in the admin bar is a bit a problem since I have 50k users. It tries to make a pull down for a large amount of users


.




Dan Wheeler
 Republican American
 389 Meadow Street
 Waterbury, CT 06722
 P: 2035743636 x1690
 C: 2032179840
 F: 2035739411
 www.rep-am.com

**Comment by MrApplejuice** [comment]
I hope at least that the next release will fix these issues.
