### ISSUE TITLE
Failed to activate plugin

### ISSUE THREAD

**Issue by ericraider33** [MrApplejuice/wp-autologin-links#9]
I have been using this plugin for a while and love it.  I was on version 1.0.8 and tried to upgrade to 1.0.10.  When I did, my WordPress crashed (everything in the site failed).  I uninstalled the plugin from disk, and was able to get back into the admin pages.  Then, I installed the latest version.  When trying to activate it, I get the following error:

Plugin could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected '[' in /var/www/html/university/wp-content/plugins/autologin-links/autologin-links.php on line 426

 - Wordpress version:  4.9.10 
 - Plugin version: 1.0.10
 - Browser (including version): Chrome

**Comment by MrApplejuice** [comment]
Hello ericraider33! Thank you very much for the very useful bug report. This will be taken into account for a future update. It is quite likely that this is a PHP-related issue.

I finally have time to do some more work on the plugin and will attempt to fix it soon.
